# Generated by Django 4.0.4 on 2022-04-17 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('F', 'First player to Move'), ('S', 'Second player to Move'), ('W', 'First player Wins'), ('L', 'Second player Wins'), ('D', 'Draw')], default='F', max_length=1),
        ),
    ]
