# Generated by Django 4.0.4 on 2022-05-01 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_room_options_room_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
